build site:
  image: node:10
  stage: build
  script:
    - yarn config set cache-folder /cache/yarn
    - yarn install
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - public


deploy:
   image: python:3
   stage: deploy
   script:
     - pip install aws-cli
     - aws s3 sync --acl public-read ./public s3://netprophet.tech
