build site:
  image: node:10
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - public


deploy:
   image: python:latest
   stage: deploy
   script:
      - pip install awscli
      - aws s3 sync --acl public-read ./public s3://netprophet.tech
