---
apiVersion: v1
kind: Service
metadata:
  name: $PROJECT
spec:
  type: ClusterIP
  ports:
  - name: $PROJECT
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: $PROJECT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECT
spec:
  selector:
    matchLabels:
      name: $PROJECT
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: $PROJECT
        app: $PROJECT
    spec:
      containers:
      - name: $PROJECT
        image: $IMAGE
        resources:
          requests:
            cpu: 250m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        imagePullPolicy: Always
        env:
          - name: SERVICE
            value: $PROJECT
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - name: $PROJECT
          containerPort: 80
          protocol: TCP
---
# Source: gitlab/charts/gitlab/charts/unicorn/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $PROJECT-http
  labels:
    app: $PROJECT
    
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "15"
    
spec:
  rules:
    - host: homepage.netprophet.tech
      http:
        paths:
          - path: /
            backend:
              serviceName: $PROJECT
              servicePort: 80
  tls:
    - hosts:
      - homepage.netprophet.tech
      secretName: homepage-netprophet-tls


