---
apiVersion: v1
kind: Service
metadata:
  name: $PROJECT
spec:
  type: ClusterIP
  ports:
  - name: $PROJECT
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: $PROJECT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECT
spec:
  selector:
    matchLabels:
      name: $PROJECT
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: $PROJECT
        app: $PROJECT
    spec:
      containers:
      - name: $PROJECT
        image: $IMAGE
        resources:
          requests:
            cpu: 250m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        imagePullPolicy: Always
        env:
          - name: SERVICE
            value: $PROJECT
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - name: $PROJECT
          containerPort: 80
          protocol: TCP
